name: github pages

on:
  push:
    branches:
      - master  # Set a branch to deploy
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
      
      - run: npm install -g gitbook-cli

      - name: Install gitbook plugin
        run: gitbook install

      - name: Build
        run: gitbook build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_book
          user_name: 'XueqiangChen'
          user_email: '569503960@qq.com'
